version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3 
    container_name: location-api-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: location_api
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7
    container_name: location-api-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: 